name: approve

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  approve:
    runs-on: ubuntu-latest
    environment: test_1

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: test Environment variables
      run: |
        echo "${{ vars.SPECIFIC_APPROVERS }}"
